# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       CSE340 Interaction Programming Notes
email:       'jial8@uw.edu'
description: 'by Jay Lin'
baseurl:     'https://jetplanejj.github.io/CSE340-private-website/' # The subpath of your site, e.g. /blog
url:         'https://type-jekyll.aspirethemes.com/' # The base hostname & protocol for your site
twitter:     'https://twitter.com/explore'
github:      'https://github.com/JetPlaneJJ/CSE340-Notes-MasterList'
instagram:   'https://www.instagram.com/j_the_egg/'
facebook:    'https://www.facebook.com/jiajiabunny/'

markdown:  kramdown
permalink: pretty
paginate:  10

kramdown:  
  parse_block_html: true

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
theme: jekyll-theme-minimal